---
- name: Install and configure Minio Server
  hosts: localhost
  become: true
  gather_facts: true
  vars:
    server_hostname: <minio.example.com>>
    ssl_key_size: 4096
    ssl_certificate_provider: selfsigned

  pre_tasks:
    - name: Generate self-signed SSL certificates for minio
      include_tasks: generate_selfsigned_cert.yml
      args:
        apply:
          delegate_to: localhost
          become: false
    - name: Load tls key and cert
      set_fact:
        minio_key: "{{ lookup('file','certificates/' + inventory_hostname + '_private.key') }}"
        minio_cert: "{{ lookup('file','certificates/' + inventory_hostname + '_public.crt') }}"

  roles:
    - role: ricsanfre.minio
      minio_root_user: "<MINIO_ADMIN>"
      minio_root_password: "<ROOT_PASSWORD>"
      minio_enable_tls: true
      minio_server_url: "https://{{ server_hostname }}:{{ minio_server_port }}"
      minio_buckets:
        - name: bucket1
          policy: read-write
        - name: bucket2
          policy: read-write
      minio_users:
        - name: <USER_1>
          password: <USER_1_PASSWORD>
          buckets_acl:
            - name: bucket1
              policy: read-write
            - name: bucket2
              policy: read-only